<?xml version="1.0"?>
<robot name="roamr_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="roamr_legwheel.xacro.xml"/> 

  <!-- SI Units -->
  <xacro:arg name="namespace" default="roamr" />
  <xacro:arg name="geom_file" default="$(find roamr_description)/config/roamr_geometry.yaml" />
  <xacro:property name="ns" value="'$(arg namespace)'" />
  <xacro:property name="geom" value="${xacro.load_yaml('$(arg geom_file)')}" />

  <xacro:property name="zc" value="${geom['wheel_radius'] + geom['caster_height']}" />
  <xacro:property name="rw" value="${geom['wheel_radius']}" />
  <xacro:property name="ll" value="${geom['leg_length']}" />

  <!-- Start with the chassis as base_link -->
  <link name="${ns}_base_link">
    <visual>
      <geometry>
        <mesh filename="package://roamr_description/meshes/roamr_chassis.dae" />
      </geometry>
    </visual>
  </link>

  <xacro:macro name="calculate_legwheel_origin" params="angle">
    <!-- Here, radius is the distance from center of chassis to vertex -->
    <xacro:property name="radius" value="${geom['chassis_side_length'] / sqrt(3)}" />
    <xacro:property name="x" value="${radius * cos(angle)}" />
    <xacro:property name="y" value="${radius * sin(angle)}" />
    <origin rpy="0.0 0.0 ${angle}" xyz="${x} ${y} 0.0" />
  </xacro:macro>

  <!-- Add the leg-wheels -->
  <xacro:roamr_legwheel zc="${zc}" rw="${rw}" ll="${ll}" parent="${ns}_base_link" prefix="${ns}" suffix="right">
    <xacro:calculate_legwheel_origin angle="${-pi/3.0}" />
  </xacro:roamr_legwheel>

  <xacro:roamr_legwheel zc="${zc}" rw="${rw}" ll="${ll}" parent="${ns}_base_link" prefix="${ns}" suffix="left">
    <xacro:calculate_legwheel_origin angle="${pi/3.0}" />
  </xacro:roamr_legwheel>
  
  <xacro:roamr_legwheel zc="${zc}" rw="${rw}" ll="${ll}" parent="${ns}_base_link" prefix="${ns}" suffix="back">
    <xacro:calculate_legwheel_origin angle="${pi}" />
  </xacro:roamr_legwheel>
  
  <link name="${ns}_base_footprint" />
  <joint name="${ns}_base_footprint_joint" type="fixed">
    <parent link="${ns}_base_link" />
    <child link="${ns}_base_footprint" />
    <origin rpy="0 0 0" xyz="0 0 -${zc}" />
  </joint>
</robot>

